
#if you can't handle me at my uwu you dont deserve me at my owo - melkey, probably
uwus = [
    'uWu',
    'oWo',
    'UWU :3',
    'UwU',
    ':3',
    'nyxiative\'s mouse pad',
    '(ᵘʷᵘ)',
    '(ᵘﻌᵘ)',
    '˯˽˯',
    '(◡ ω ◡)',
    '(◡ u ◡)',
    '(◡ w ◡)',
    '(◡ ሠ ◡)',
    '(˘ω˘)',
    '(⑅˘꒳˘)',
    '(˘ᵕ˘)',
    '(˘ሠ˘)',
    '(˘³˘)',
    '(˘ε˘)',
    '(´˘`)',
    '(´^`)',
    '(˘ ^ ˘)',
    '( ᴜ ω ᴜ )',
    '( ´ω` )۶',
    '(„ᵕᴗᵕ„)',
    '(*ฅ́˘ฅ̀*) ',
    '(ㅅ ˘ )',
    '(⑅˘˘)',
    '( ｡ᵘ ᵕ ᵘ ｡)'
]
